version: '3.9'

services:
  db:
    image: postgres:15
    container_name: task_pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: task_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
